version: '3.4'

services:
  vilmar.postgres:
    image: postgres:latest
    container_name: vilmar.postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432

  vilmar.rabbitmq:
    image: rabbitmq:3-management
    container_name: vilmar.rabbitmq
    volumes:
      - ./.containers/rabbitmq:/var/lib/rabbitmq/data
    ports: 
      - 15672:15672
      - 5672:5672

  vilmar.realtime.chat:
    image: ${DOCKER_REGISTRY-}vilmarrealtimechat
    build:
      context: .
      dockerfile: Vilmar.Realtime.Chat/Dockerfile
